services:
  hysteria:
    image: tobyxdd/hysteria:v2
    container_name: hysteria
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./hysteria/acme:/var/lib/hysteria/acme
      - ./hysteria/config.yml:/etc/hysteria/config.yaml
    command: ["server", "-c", "/etc/hysteria/config.yaml"]

  bot:
    image: oven/bun:latest
    container_name: hysteria-bot
    restart: always
    working_dir: /app
    network_mode: "host"
    volumes:
      - ./bot:/app
      - ./data:/app/data
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c", "bun install && bun --watch src/index.js"]
